import spmpool
# pool = spmpool.spmpool()
spmpool.add_config('local', 'root', '123456', 'test')
pool = spmpool.spmpool('local')
print('init_pool_size:', pool.size())
conn = pool.get()
print('after get one size:', pool.size())
result = conn.execute('select 2,3,4')
print('result auto bind on conn:', conn.result == result)
row1 = result.first()
print(row1.col0, '--row1:column1 2 ways to get--', row1[0])
conn.close()
print('after conn close size:', pool.size())
pool.shutdown()